### ISSUE TITLE
Неправильное отображение отправителей и получателей

### ISSUE THREAD

**Issue by Zhenyatin** [xQxQ222/SchoolHelper#7]
Я зашла с аккаунта xQxQA, отправила сообщение, а среди получателей указана я же. Перепутаны местами получатель и отправитель
![image](https://github.com/xQxQ222/SchoolHelper/assets/152517347/0d6663d9-de36-43d4-8d45-9a4de60039d5)

**Comment by xQxQ222** [comment]
Исправлено
